### ISSUE TITLE
Nobrighter is a very good userscript,but I have a little problem,using it.

### ISSUE THREAD

**Issue by N1CEyk** [henix/userjs#5]
When I use it in YTB,I can't see the  video's  cache progress bar,because it is covered by green lines.Can you solve it,please?

**Comment by henix** [comment]
用中文吧。截个图吧，我看看

**Comment by N1CEyk** [comment]
看到用中文莫名的笑了，哈哈哈，缓存条被绿色完全盖住了

​

2016-06-01 13:34 GMT+08:00 henix <notifications@github.com>:

**Comment by henix** [comment]
求截图啊，我不知道你说的是哪一个...

**Comment by N1CEyk** [comment]
放大给你看

2016-06-01 17:04 GMT+08:00 henix <notifications@github.com>:

**Comment by N1CEyk** [comment]
红框里的缓存进度全被绿色盖住了

2016-06-01 17:07 GMT+08:00 Yk Yang <n1ce0571@gmail.com>:

**Comment by henix** [comment]
我发现，似乎你之前就上传了截图，但为啥我什么也看不到 ╮(￣▽￣")╭（见下）

![image](https://cloud.githubusercontent.com/assets/288251/15704194/1f615576-281c-11e6-922d-c07f73f84539.png)

难道你是回复的邮件？我直接在 https://github.com/henix/userjs/issues/5 看不到，我在邮件里也看不到的。你直接在 Github 的回复框里上传吧。

**Comment by N1CEyk** [comment]
在 2016年6月1日 下午5:17，henix <notifications@github.com>写道：

**Comment by N1CEyk** [comment]
![Uploading 1.png…]()

不知道你看到没，再发一遍图

**Comment by N1CEyk** [comment]
可以看到图了吗

在 2016年6月1日 下午5:22，Yk Yang <n1ce0571@gmail.com>写道：

**Comment by henix** [comment]
还是没有...你直接用浏览器访问这个地址：`https://github.com/henix/userjs/issues/5`是看不到的

**Comment by N1CEyk** [comment]
这个网站图片我也传不上去，没办法我分享在百度云上了
http://pan.baidu.com/s/1nvLBh8X


2016-06-01 19:09 GMT+08:00 henix <notifications@github.com>:

**Comment by henix** [comment]
我自己这边看到的是这样的：
![image](https://cloud.githubusercontent.com/assets/288251/15709537/d5cb0756-2837-11e6-980e-becebbdaba68.png)
不能重现，你是不是自己改过 `Brightness_Threshold`

**Comment by N1CEyk** [comment]
代码我没动过，如果进一个频道，最开始的频道介绍的视频其缓存是可以看到的如你上图一直，但你点这个频道的其他任意一个视频，缓存条就会被绿色盖住，你试试

2016-06-01 20:32 GMT+08:00 henix <notifications@github.com>:

**Comment by henix** [comment]
我看到了。这个我目前的策略是将亮度高于某一阈值的颜色都改掉，以后可以考虑的策略是如果一个元素的高度太小就不修改。这也许是一个有意思的改进方向。我最近有空会改一下。

**Comment by N1CEyk** [comment]
谢谢，如果可以提供一个颜料库，可以供用户选择自己喜欢的背景色就更完美了

在 2016年6月2日 上午11:49，henix <notifications@github.com>写道：

**Comment by henix** [comment]
这是油猴脚本的限制，选项这种不好做的，目前没找到什么比较好的方案。

**Comment by N1CEyk** [comment]
仅仅是个人一个想法，只是出于对美好事物的追求，别在意

2016-06-08 5:49 GMT+08:00 henix <notifications@github.com>:
